questions = [
    "LangChain v0.3版本中提到的Model I/O包含哪三个核心环节？",
    "在LangChain中初始化模型时，推荐将API-KEY和BASE_URL写在哪里？为什么？",
    "使用ChatDeepSeek初始化模型时，api_base参数的默认值是什么？",
    "为什么在使用ChatTongyi调用阿里云百炼平台时，通常不建议设置DASHSCOPE_BASE_URL环境变量？",
    "OpenRouter平台的主要特点是什么？国内用户使用时有什么限制？",
    "init_chat_model()函数相比直接使用ChatOpenAI或ChatDeepSeek等专用类有什么优势？",
    "在使用init_chat_model时，如果model参数为\"qwen-plus\"但未指明model_provider，会发生什么？",
    "temperature参数设置为0.0和1.5分别适用于什么场景？",
    "在大模型中，Token的估算规则是怎样的？",
    "Ollama是什么？它在LangChain中如何被调用？",
    "invoke()方法的输入参数支持哪三种形式？",
    "在多轮对话中，如果不传递历史消息，AI会出现什么问题？如何解决？",
    "AIMessage返回值中的finish_reason为\"length\"表示什么？",
    "stream()方法相比invoke()有什么优点？",
    "batch()方法与循环调用invoke()相比，性能上有什么优势？",
    "ainvoke()与invoke()的核心区别是什么？",
    "如何通过config参数在运行时动态覆盖模型初始化时设置的temperature？",
    "如何查看ChatDeepSeek类支持的完整参数列表？",
    "model_kwargs和extra_body参数有什么区别？",
    "什么是Agent？其核心组件有哪些？",
    "LangChain 1.0版本后创建Agent的统一入口函数是什么？它取代了哪些旧函数？",
    "create_agent()返回的对象本质上是什么类型？",
    "agent.invoke()的输入和输出格式分别是什么？",
    "Agent如何选择使用哪个工具？",
    "为什么建议只给Agent绑定2-5个工具？",
    "当工具返回临时故障信息时，如何让Agent自主重试？",
    "如何判断Agent已经完成任务？",
    "如何限制Agent的工具调用次数以防止无限循环？",
    "为Agent设置name参数有哪些实际用途？",
    "system_prompt参数支持哪两种类型？",
    "Agent的结构化输出与模型的结构化输出有何区别？",
    "create_agent的response_format参数支持哪四种策略？",
    "ToolStrategy实现结构化输出的核心原理是什么？",
    "使用ToolStrategy时，结构化数据最终存储在返回结果的哪个键中？",
    "tool_message_content参数的作用是什么？",
    "handle_errors=True时，Agent如何处理结构化输出错误？",
    "MultipleStructuredOutputsError异常在什么情况下触发？",
    "stream_mode=\"values\"和stream_mode=\"updates\"有什么区别？",
    "哪种stream_mode最适合实现类似ChatGPT的打字机效果？",
    "custom流式输出模式如何实现自定义进度信息？",
    "checkpoints流式输出模式适用于什么场景？",
    "是否可以同时使用多种stream_mode？如果可以，如何遍历结果？",
    "在多功能智能助手实战中，calculator工具支持哪些数学函数？",
    "convert_currency工具的汇率转换逻辑是怎样的？",
    "在Agent结构化输出中，如果system_prompt先要求输出结构化结果再调用工具，可能导致什么问题？",
    "AutoStrategy在选择结构化输出策略时的优先级是什么？",
    "TypedDict类型的Schema是否支持运行时验证？",
    "当handle_errors设置为自定义callable时，该函数的返回值会被用作什么？",
    "在Agent调用流程中，一次完整的Function Calling包含哪四类消息？"
]

ground_truths = [
    ["Format（输入提示/Prompt Template）、Predict（调用模型/Model）、Parse（输出解析/Output Parser）。"],
    ["推荐使用配置文件（如.env文件）。因为硬编码写在代码中存在密钥泄露风险，而配置文件可加入.gitignore避免泄露，且便于环境管理。"],
    ["https://api.deepseek.com/v1"],
    ["因为ChatTongyi底层是基于专用SDK实现的，而DASHSCOPE_BASE_URL是为OpenAI兼容接口准备的。如果指定了该URL，会导致ConnectionError报错。"],
    ["OpenRouter是一个多模型API聚合平台，提供统一的OpenAI兼容接口，支持支付宝/微信充值。限制是：如果调用的模型禁止在国内使用（如ChatGPT），无法直接调用，会提示\"This model is not available in your region\"。"],
    ["1. 统一接口，无需记忆每个提供商的初始化方式；2. 易于切换模型，只需修改模型字符串；3. 语法简洁，减少样板代码；4. 自动适配，根据模型标识自动选择对应的驱动类。"],
    ["会报错。因为并非所有模型都支持自动推断供应商，qwen-plus不支持自动推断，必须通过model_provider参数或在model前缀中指明供应商。"],
    ["0.0适用于需要一致性、准确性的任务（如数学计算、数据提取、代码生成）；1.5适用于高度创造性任务（如诗歌、故事创作）。"],
    ["英文：1 token ≈ 4字符 ≈ 0.75单词；中文：1 token ≈ 1-2汉字。"],
    ["Ollama是一个本地运行大模型的集成框架，支持Qwen、Deepseek等模型的下载与部署。在LangChain中可通过ChatOllama类或init_chat_model(model_provider=\"ollama\")进行调用。"],
    ["1. 文本输入（str）；2. 字典列表（list[dict]，推荐）；3. 消息对象列表（list[Message]）。"],
    ["AI会\"失忆\"，无法记住之前的对话内容。解决方法是在每次调用invoke时，将之前的对话历史（包括user和assistant的消息）一并传入messages列表。"],
    ["表示模型输出达到了max_tokens限制而被截断，并非自然结束。"],
    ["响应速度更快，用户不必等待完整输出；交互体验更流畅，尤其适合长文本或聊天机器人场景；可实时展示模型思考过程。"],
    ["batch()允许一次性发送一组请求并行处理，大幅减少网络往返开销和等待时间。文档示例显示批量调用比循环调用节省约50%的时间。"],
    ["invoke()是阻塞式的，程序需等待响应完成；ainvoke()是非阻塞异步调用，发起任务后可继续执行其他逻辑，提高系统吞吐量和资源利用率。"],
    ["在invoke时传入config={\"configurable\": {\"temperature\": 0.7}}，但前提是初始化模型时需通过configurable_fields指定temperature为可替换参数。"],
    ["通过访问类属性ChatDeepSeek.model_fields.keys()来获取完整参数列表，包括自身定义和从BaseChatModel继承的参数。"],
    ["model_kwargs用于传递OpenAI Compatible API支持但LangChain未定义的字段（如tools）；extra_body用于传递模型厂商基于OpenAI协议扩展的字段（如DeepSeek的thinking）。"],
    ["Agent是以大语言模型为推理决策核心，结合记忆、工具调用与环境交互能力，能规划决策并执行复杂任务的软件系统。核心组件包括：行动（Action，必须）、工具（Tool，几乎总是存在）、规划决策（Planning，有条件存在）、记忆（Memory，最易被省略）。"],
    ["create_agent()。它取代了create_react_agent、create_json_agent、create_tool_calling_agent等多种分支函数。"],
    ["langgraph.graph.state.CompiledStateGraph，即一个LangGraph的图结构实例。"],
    ["输入为字典{\"messages\": [消息列表]}；输出也为字典，包含完整的消息列表{\"messages\": [...]},最终回答通常是response['messages'][-1].content。"],
    ["AI根据工具的docstring描述、用户问题内容以及system_prompt中的说明，自动选择最匹配的工具。"],
    ["工具太多会导致模型混淆，难以准确选择正确的工具，影响任务执行效果。"],
    ["在system_prompt中明确指示：当工具返回特定错误标识（如TEMP_UNAVAILABLE）时，应再次调用同一工具，最多重试N次，若仍失败再向用户说明。"],
    ["当返回的AIMessage不包含tool_calls字段（或tool_calls为空）时，表示Agent已完成任务并给出了最终答案。"],
    ["在调用agent.invoke时传入config={\"recursion_limit\": N}，其中N为最大递归/调用步数。"],
    ["1. 流式输出归因；2. 消息身份标记；3. 调试与trace可读性；4. 组件化封装；5. 前端展示与运行态可观测性；6. 作为稳定的运行时身份标识。"],
    ["str类型和SystemMessage类型。"],
    ["模型结构化输出作用于模型对象，每次生成AIMessage时解析；Agent结构化输出作用于Agent，仅在任务结束输出最终答案时解析，且支持多步推理后的结构化汇总。"],
    ["ProviderStrategy、ToolStrategy、AutoStrategy（或直接传type）、None。"],
    ["动态创建一个\"虚拟工具\"，其输入参数对应期望的数据结构，引导模型通过调用该虚拟工具来生成符合要求的结构化数据。"],
    ["result[\"structured_response\"]。"],
    ["自定义生成结构化输出时会话历史中记录的提示信息，用简短确认信息替代原始数据块，减少token消耗并使对话流更友好。"],
    ["捕获所有异常，使用LangChain内置的错误消息模板提示模型重试，直到成功或达到最大重试次数。"],
    ["当使用Union类型定义多个Schema时，模型错误地返回了多个结构化响应（工具调用请求数量大于1），而系统期望只返回一个。"],
    ["values模式每步输出完整状态信息，适用于状态持久化；updates模式只增量更新变化的内容，适用于监控执行进度。"],
    ["messages模式，它会流式返回Token及相关元数据。"],
    ["在工具或节点内部通过get_stream_writer()获取写入器，然后调用writer(data)发送自定义数据。"],
    ["需要状态持久化、工作流恢复或分布式执行跟踪的高级场景。"],
    ["可以，传入列表如stream_mode=[\"tasks\", \"updates\"]。遍历时使用for stream_mode, chunk in agent.stream(...)，其中stream_mode是模式名，chunk是对应结果。"],
    ["sqrt, pow, abs, round, sin, cos, tan, log, pi, e。"],
    ["先将源货币金额转换为CNY（人民币），再将CNY金额转换为目标货币。公式：cny_amount = amount / exchange_rates[from_curr]; result = cny_amount * exchange_rates[to_curr]。"],
    ["可能导致一些工具不会再被调用，因为Agent可能认为任务已经完成。建议在system_prompt最后提示结构化输出结果。"],
    ["优先使用ProviderStrategy（如果模型支持原生结构化输出），否则回退到ToolStrategy。"],
    ["不支持。TypedDict仅提供类型提示，不进行运行时数据验证。"],
    ["作为ToolMessage的内容反馈给模型，指导其重试。"],
    ["HumanMessage（用户发起）、AIMessage（含tool_calls）、ToolMessage（工具返回结果）、AIMessage（最终回答）。"]
]